try {
    syscall io_out("No error thrown\n");
} catch (error) {
    syscall io_out("Caught error that does not exist\n");
}

try {
    throw 1;
}

try {
    throw 2;
} catch (error) {
    syscall io_out("Caught error: ");
    syscall io_out(error);
    syscall io_out("\n");
}

function rethrow() {
    try {
        throw 3;
    } catch (error) {
        throw error + 1;
    }
}

try {
    rethrow();
} catch (error) {
    syscall io_out("Caught error: ");
    syscall io_out(error);
    syscall io_out("\n");
}

try {
    throw 5;
}